// Build the sticky PR-comment markdown from artifacts/fidelity/report.json.
// If MONTAGE_URL_BASE is set (Phase 2), each fixture's OSS|JS|diff montage is
// embedded inline (collapsible); otherwise the comment is the table alone.
//
// Usage: node tools/fidelity_comment.mjs
// Env:
//   MONTAGE_URL_BASE  e.g. https://raw.githubusercontent.com/OWNER/REPO/ci-fidelity/pr-13
//                     (each fixture image is <base>/<fixture>.png)
//   CACHE_BUST        appended as ?v=<value> so updated images refresh (e.g. head SHA)
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const OUT = path.join(process.cwd(), 'artifacts', 'fidelity');
const report = JSON.parse(readFileSync(path.join(OUT, 'report.json'), 'utf8'));
const { tolerance, results } = report;
const urlBase = process.env.MONTAGE_URL_BASE || '';
const bust = process.env.CACHE_BUST ? `?v=${process.env.CACHE_BUST}` : '';

const regressed = results.filter((r) => r.regressed);
const errored = results.filter((r) => !r.ok);

const statusOf = (r) =>
  !r.ok ? '🟥 error' : r.regressed ? '🔴 regressed' : r.baseline_pct == null ? '🆕 new' : '🟢 ok';

const header = regressed.length
  ? `### ❌ Fidelity: ${regressed.length} fixture(s) regressed vs OpenStrandStudio`
  : errored.length
    ? `### ⚠️ Fidelity: ${errored.length} fixture(s) failed to render`
    : `### ✅ Fidelity: JS renderer matches the OpenStrandStudio Qt oracle`;

const rows = results.map((r) => {
  const match = r.ok ? `${r.match_pct}%` : '—';
  const base = r.baseline_pct != null ? `${r.baseline_pct}%` : '—';
  const delta = r.delta != null ? (r.delta >= 0 ? `+${r.delta}` : `${r.delta}`) : '—';
  return `| \`${r.fixture}\` | ${statusOf(r)} | ${match} | ${base} | ${delta} |`;
});

const pagesUrl = process.env.PAGES_URL || '';
const lines = [
  '<!-- fidelity-bot -->',
  header,
  '',
  `Each fixture is rendered by the **real OpenStrandStudio Qt canvas** (the pixel oracle) and by the **JS/Paper.js renderer**, then pixel-diffed (AA-tolerant). A fixture fails the gate if its match% drops more than **${tolerance}** points below baseline, or fails to render.`,
  '',
  ...(pagesUrl ? [`📊 **[View the full dashboard for this PR →](${pagesUrl})**  ·  canonical (main): <https://ysetbon.github.io/OpenStrandJS/fidelity/>`, ''] : []),
  '| Fixture | Status | Match | Baseline | Δ |',
  '| --- | --- | --- | --- | --- |',
  ...rows,
  '',
];

if (urlBase) {
  lines.push('<details><summary>🖼️ OSS · JS · diff renders</summary>', '');
  for (const r of results) {
    if (!r.ok) { lines.push(`**\`${r.fixture}\`** — render error:`, '```', (r.error || '').slice(-400), '```', ''); continue; }
    const badge = r.regressed ? ' 🔴' : '';
    lines.push(`**\`${r.fixture}\`** — ${r.match_pct}% (OSS | JS | diff)${badge}`);
    lines.push(`![${r.fixture}](${urlBase}/${r.fixture}.png${bust})`, '');
  }
  lines.push('</details>', '');
}

lines.push('---', '_Generated by [Claude Code](https://claude.ai/code) · OSS-vs-JS fidelity bot_');
writeFileSync(path.join(OUT, 'comment.md'), lines.join('\n'));
console.log(`comment -> ${path.join(OUT, 'comment.md')}${urlBase ? ' (with inline montages)' : ' (table only)'}`);
