// Selection-footprint PARITY harness: OpenStrand Studio vs OpenStrandJS, for the
// yellow hover highlight and the click hit-area in select and mask mode.
//
// For every case in fixtures/selection/manifest.json (one scene per end-cap /
// side-line / circle / mask configuration, generated by
// tools/make_selection_cases.py):
//   1. [--oss] tools/oss_selection_capture.py renders the case through the REAL
//      Qt app: strands + its exact hover overlay, and a per-pixel hit map of
//      selection_utils.find_strands_at_point() -> artifacts/selection/<key>/
//   2. the live editor (a Vite dev server started here) renders the same case at
//      the same geometry, hovering the same layer in the same mode, and a hit map
//      of hitTest / maskStrandsAtPoint is sampled at the same pixels
//   3. both are cropped to the scene, pixel-diffed, and written into one HTML
//      report (artifacts/selection/report.html) with a summary table.
//
// Usage: node tools/selection_parity.mjs [--oss] [--tag after] [--cases a,b]
//   --oss    (re)run the OSS captures first (needs a Python with PyQt5 + Pillow and
//            the OpenStrandStudio checkout: OSS_ROOT, default ../OpenStrandStudio;
//            PYTHON overrides the interpreter). Without it, the existing OSS
//            captures under artifacts/selection are reused.
//   --tag    name of the JS capture set (default 'after'); the report shows every
//            tag it finds, so `--tag before` on the old code then `--tag after` on
//            the new one gives a before/after page.
// Env: OSS_CHROMIUM  a Chromium binary for Playwright (optional).
// Exit code 1 if any case's hit area differs from OSS by more than HIT_TOLERANCE_PX
// (single edge pixels along curved strands are Qt-vs-polyline flattening noise).

import { chromium } from 'playwright';
import { createServer } from 'vite';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';
import pixelmatch from 'pixelmatch';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const casesDir = path.join(root, 'fixtures', 'selection');
const outRoot = path.join(root, 'artifacts', 'selection');
const args = process.argv.slice(2);
const flag = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : undefined; };
const runOss = args.includes('--oss');
const tag = flag('--tag') || 'after';
const only = flag('--cases')?.split(',').map((s) => s.trim()).filter(Boolean);
const HIT_TOLERANCE_PX = 80;

const manifest = JSON.parse(readFileSync(path.join(casesDir, 'manifest.json'), 'utf8'))
  .filter((c) => !only || only.includes(c.key));
mkdirSync(outRoot, { recursive: true });

// --- 1. OSS captures ----------------------------------------------------------
if (runOss) {
  const PY = process.env.PYTHON || 'python3';
  const env = { ...process.env, QT_QPA_PLATFORM: process.env.QT_QPA_PLATFORM || 'offscreen' };
  for (const c of manifest) {
    console.log(`OSS capture ${c.key} (hover ${c.hover}, ${c.mode})…`);
    execFileSync(PY, [path.join(root, 'tools', 'oss_selection_capture.py'),
      path.join(casesDir, c.key + '.json'), c.hover, c.mode, path.join(outRoot, c.key)], { env, stdio: 'inherit' });
  }
}

// --- 2. JS captures ------------------------------------------------------------
const server = await createServer({
  root, configFile: path.join(root, 'vite.config.ts'),
  server: { port: 5219, open: false, host: '127.0.0.1' }, logLevel: 'error',
});
await server.listen();
const browser = await chromium.launch(
  process.env.OSS_CHROMIUM ? { executablePath: process.env.OSS_CHROMIUM } : {});
const pageErrors = [];
try {
  const page = await browser.newPage({ viewport: { width: 1000, height: 800 }, deviceScaleFactor: 1 });
  page.on('pageerror', (e) => pageErrors.push(String(e)));
  await page.goto('http://127.0.0.1:5219/', { waitUntil: 'load', timeout: 60000 });
  await page.waitForFunction(() => !!window.__store && !!window.__io && !!window.__hit, null, { timeout: 30000 });

  for (const c of manifest) {
    const dir = path.join(outRoot, c.key);
    const metaPath = path.join(dir, 'meta.json');
    if (!existsSync(metaPath)) { console.log(`skip ${c.key}: no OSS capture (run with --oss)`); continue; }
    const meta = JSON.parse(readFileSync(metaPath, 'utf8'));
    const fixture = JSON.parse(readFileSync(path.join(casesDir, c.key + '.json'), 'utf8'));

    const res = await page.evaluate(async ({ fixture, meta, hover, mode }) => {
      const S = window.__store;
      const raf = () => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)));
      const st = S.getState();
      st.setSettings({ curve_params: meta.curve_params, show_grid: false, show_hover_highlights: true, theme: 'default' });
      const doc = window.__io.loadProject(fixture);
      doc.shadow_enabled = false;
      st.loadDocument(doc);
      // Same world->pixel mapping as the OSS image: zoom 1, pan = OSS content offset.
      st.setView({ panX: meta.x_offset, panY: meta.y_offset, zoom: 1, supersample: 1 });
      st.setMode(mode);
      st.setSelection({ layerName: null, handle: null });
      st.setMaskPending([]);
      st.setHover({ layerName: hover, handle: null });
      window.__requestRender(); window.__requestOverlay();
      await raf(); await raf(); await raf();
      const cv = document.getElementById('c'), ov = document.getElementById('overlay');
      const t = document.createElement('canvas'); t.width = cv.width; t.height = cv.height;
      const ctx = t.getContext('2d');
      ctx.fillStyle = 'white'; ctx.fillRect(0, 0, t.width, t.height);
      ctx.drawImage(cv, 0, 0); ctx.drawImage(ov, 0, 0);
      const [x0, y0, x1, y1] = meta.crop;
      const w = x1 - x0, h = y1 - y0;
      const hitIdx = new Int16Array(w * h).fill(-1);
      const d = S.getState().doc, s = S.getState().settings;
      for (let py = y0; py < y1; py++) {
        for (let px = x0; px < x1; px++) {
          const world = { x: px - meta.x_offset, y: py - meta.y_offset };
          let name = null;
          if (mode === 'mask') { const at = window.__hit.maskStrandsAtPoint(world, d, s); name = at.length ? at[0] : null; }
          else { const r = window.__hit.hitTest(world, d, s); name = r ? r.layerName : null; }
          if (name) hitIdx[(py - y0) * w + (px - x0)] = meta.layers.indexOf(name);
        }
      }
      return { url: t.toDataURL('image/png'), hit: Array.from(hitIdx) };
    }, { fixture, meta, hover: c.hover, mode: c.mode });

    writeFileSync(path.join(dir, `${tag}_hover.png`), Buffer.from(res.url.split(',')[1], 'base64'));
    const [x0, y0, x1, y1] = meta.crop;
    const w = x1 - x0, h = y1 - y0;
    const hit = new PNG({ width: w, height: h });
    for (let i = 0; i < w * h; i++) {
      const li = res.hit[i];
      const col = li >= 0 ? meta.hit_colors[li % meta.hit_colors.length] : [255, 255, 255];
      hit.data[i * 4] = col[0]; hit.data[i * 4 + 1] = col[1]; hit.data[i * 4 + 2] = col[2]; hit.data[i * 4 + 3] = 255;
    }
    writeFileSync(path.join(dir, `${tag}_hit.png`), PNG.sync.write(hit));
    console.log(`JS capture ${c.key} -> ${tag}`);
  }
} finally {
  await browser.close();
  await server.close();
}

// --- 3. Crop, diff, report ----------------------------------------------------
function crop(png, [x0, y0, x1, y1]) {
  const w = x1 - x0, h = y1 - y0;
  const out = new PNG({ width: w, height: h });
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const si = ((y + y0) * png.width + (x + x0)) * 4, di = (y * w + x) * 4;
    const inside = y + y0 < png.height && x + x0 < png.width;
    out.data[di] = inside ? png.data[si] : 255; out.data[di + 1] = inside ? png.data[si + 1] : 255;
    out.data[di + 2] = inside ? png.data[si + 2] : 255; out.data[di + 3] = 255;
  }
  return out;
}
const read = (p) => PNG.sync.read(readFileSync(p));
const dataUri = (png) => 'data:image/png;base64,' + PNG.sync.write(png).toString('base64');
function hoverDiff(a, b) {
  const out = new PNG({ width: a.width, height: a.height });
  const n = pixelmatch(a.data, b.data, out.data, a.width, a.height, { threshold: 0.12, diffColor: [220, 30, 30], diffColorAlt: [30, 90, 220], alpha: 0.25 });
  return { n, png: out };
}
function hitDiff(a, b) {
  const out = new PNG({ width: a.width, height: a.height });
  let n = 0, total = 0;
  for (let i = 0; i < a.width * a.height; i++) {
    const same = a.data[i * 4] === b.data[i * 4] && a.data[i * 4 + 1] === b.data[i * 4 + 1] && a.data[i * 4 + 2] === b.data[i * 4 + 2];
    const aHit = !(a.data[i * 4] === 255 && a.data[i * 4 + 1] === 255 && a.data[i * 4 + 2] === 255);
    const bHit = !(b.data[i * 4] === 255 && b.data[i * 4 + 1] === 255 && b.data[i * 4 + 2] === 255);
    if (aHit || bHit) total++;
    let c = [245, 245, 245];
    if (!same) { n++; c = aHit && !bHit ? [220, 30, 30] : (!aHit && bHit ? [30, 90, 220] : [230, 150, 20]); }
    else if (aHit) c = [200, 200, 200];
    out.data[i * 4] = c[0]; out.data[i * 4 + 1] = c[1]; out.data[i * 4 + 2] = c[2]; out.data[i * 4 + 3] = 255;
  }
  return { n, total, png: out };
}

const rows = [];
const tags = new Set();
for (const c of manifest) {
  const dir = path.join(outRoot, c.key);
  if (!existsSync(path.join(dir, 'meta.json'))) continue;
  const meta = JSON.parse(readFileSync(path.join(dir, 'meta.json'), 'utf8'));
  const ossHover = crop(read(path.join(dir, 'oss_hover.png')), meta.crop);
  const ossHit = read(path.join(dir, 'oss_hit.png'));
  const cols = { oss: { hover: dataUri(ossHover), hit: dataUri(ossHit) } };
  const stats = {};
  for (const t of ['before', 'after', tag]) {
    const hp = path.join(dir, `${t}_hover.png`);
    if (!existsSync(hp) || cols[t]) continue;
    tags.add(t);
    const jh = crop(read(hp), meta.crop), jhit = read(path.join(dir, `${t}_hit.png`));
    const d = hoverDiff(ossHover, jh), hd = hitDiff(ossHit, jhit);
    cols[t] = { hover: dataUri(jh), hit: dataUri(jhit), hoverDiff: dataUri(d.png), hitDiff: dataUri(hd.png) };
    stats[t] = { hoverDiffPx: d.n, hitDiffPx: hd.n, hitTotal: hd.total, hitPct: +(100 * hd.n / Math.max(1, hd.total)).toFixed(2) };
  }
  rows.push({ ...c, meta, cols, stats, w: ossHover.width });
}
const tagList = ['before', 'after', tag].filter((t, i, a) => tags.has(t) && a.indexOf(t) === i);
console.table(rows.map((r) => Object.fromEntries([['case', r.key], ...tagList.flatMap((t) => [[`${t} hover px`, r.stats[t]?.hoverDiffPx ?? '-'], [`${t} hit px`, r.stats[t]?.hitDiffPx ?? '-']])])));

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
const groups = [...new Set(rows.map((r) => r.group))];
const legend = (r) => r.meta.layers.map((n, i) => `<span class="lg"><i style="background:rgb(${r.meta.hit_colors[i % r.meta.hit_colors.length].join(',')})"></i>${esc(n)}</span>`).join('');
const cell = (src, cap, w) => `<figure><img src="${src}" width="${w}" alt="${esc(cap)}"><figcaption>${cap}</figcaption></figure>`;
const verdict = (s) => !s ? '' : (s.hitDiffPx === 0 ? '<b class="ok">identical hit area</b>' : `<b class="${s.hitDiffPx > HIT_TOLERANCE_PX ? 'bad' : 'ok'}">${s.hitDiffPx} px differ (${s.hitPct}% of the hit area)</b>`);
const rowHtml = (r) => {
  const w = Math.min(r.w, 300);
  const strip = (kind) => tagList.map((t) => r.cols[t] ? cell(r.cols[t][kind], `OSSJS ${t}`, w) + cell(r.cols[t][kind + 'Diff'], `${kind} diff · ${t}: ${kind === 'hit' ? verdict(r.stats[t]) : r.stats[t].hoverDiffPx + ' px'}`, w) : '').join('');
  return `
<section class="case" id="${r.key}">
  <h3>${esc(r.title)} <small>hover <code>${esc(r.hover)}</code> · ${r.mode} mode</small></h3>
  <p class="what">${esc(r.what)}</p>
  <div class="strip"><div class="lbl">Yellow hover highlight</div>${cell(r.cols.oss.hover, 'OSS (Qt, the spec)', w)}${strip('hover')}</div>
  <div class="strip"><div class="lbl">Hit area (which layer a click / hover resolves to, per pixel) ${legend(r)}</div>${cell(r.cols.oss.hit, 'OSS find_strands_at_point', w)}${strip('hit')}</div>
</section>`;
};
const totals = (t) => {
  const rs = rows.filter((r) => r.stats[t]);
  return rs.length ? { n: rs.length, bad: rs.filter((r) => r.stats[t].hitDiffPx > 0).length, px: rs.reduce((s, r) => s + r.stats[t].hitDiffPx, 0) } : null;
};
const html = `<title>Selection Footprint Parity</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,600&family=Source+Sans+3:wght@400;600&family=JetBrains+Mono:wght@400&display=swap">
<style>
:root{--bg:#f7f5ee;--fg:#211f1b;--mut:#6f685b;--card:#fffdf8;--line:#e3dfd2;--ok:#1f7a4a;--bad:#b8321f;--acc:#6f4fb8}
@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){--bg:#1b1a17;--fg:#ebe7dd;--mut:#a39c8e;--card:#242220;--line:#3a3731;--ok:#5fcb8a;--bad:#ff8a7a;--acc:#b59df0}}
:root[data-theme="dark"]{--bg:#1b1a17;--fg:#ebe7dd;--mut:#a39c8e;--card:#242220;--line:#3a3731;--ok:#5fcb8a;--bad:#ff8a7a;--acc:#b59df0}
body{background:var(--bg);color:var(--fg);font:16px/1.5 "Source Sans 3",system-ui,sans-serif;margin:0;padding:32px 36px 72px;max-width:1520px}
h1,h2,h3{font-family:"Source Serif 4",Georgia,serif;font-weight:600;text-wrap:balance}
h1{font-size:30px;margin:0 0 8px}h2{font-size:21px;margin:40px 0 10px;color:var(--acc)}h3{font-size:17px;margin:0 0 4px}
h3 small{font-family:"Source Sans 3",sans-serif;font-weight:400;color:var(--mut);font-size:13px;margin-left:6px}
code,.lg,table.sum td:nth-child(n+3){font-family:"JetBrains Mono",ui-monospace,Menlo,monospace;font-size:13px;font-variant-numeric:tabular-nums}
.lead{color:var(--mut);max-width:70ch}.what{margin:0 0 10px;color:var(--mut);font-size:14px;max-width:90ch}
.case{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:14px 18px;margin:14px 0}
.strip{display:flex;gap:12px;flex-wrap:wrap;align-items:flex-start;overflow-x:auto;padding:6px 0}
.lbl{flex-basis:100%;font-size:12px;letter-spacing:.04em;text-transform:uppercase;color:var(--mut)}
figure{margin:0}figure img{display:block;border:1px solid var(--line);background:#fff;max-width:100%}
figcaption{font-size:12px;color:var(--mut);margin-top:3px;max-width:300px}
.ok{color:var(--ok)}.bad{color:var(--bad)}
.lg{display:inline-flex;align-items:center;gap:4px;margin-left:10px;text-transform:none;letter-spacing:0}.lg i{width:11px;height:11px;border-radius:2px;display:inline-block}
.tblwrap{overflow-x:auto}table.sum{border-collapse:collapse;margin:12px 0;font-size:14px}table.sum td,table.sum th{border-bottom:1px solid var(--line);padding:5px 14px 5px 0;text-align:left}table.sum th{font-size:12px;letter-spacing:.04em;text-transform:uppercase;color:var(--mut);font-weight:600}
table.sum a{color:inherit}.key{font-size:13px;color:var(--mut);margin:8px 0 0}.key i{display:inline-block;width:11px;height:11px;border-radius:2px;margin:0 4px 0 12px;vertical-align:-1px}
</style>
<h1>Selection footprint: OpenStrand Studio vs OpenStrandJS</h1>
<p class="lead">Every case is rendered by the <b>real OpenStrand Studio</b> (PyQt5, offscreen) with its actual select/mask-mode hover overlay, and by the <b>live OpenStrandJS editor</b> at the same geometry (zoom 1, supersample 1). The hit maps are not drawings: each pixel is the answer of OSS's <code>find_strands_at_point</code> and of OSSJS's <code>hitTest</code> / <code>maskStrandsAtPoint</code> at that position.</p>
<p class="key">Hit-diff colours: <i style="background:#dc1e1e"></i>OSS hits, OSSJS misses <i style="background:#1e5adc"></i>OSSJS hits, OSS misses <i style="background:#e69614"></i>different layer wins <i style="background:#c8c8c8"></i>agree (hit) <i style="background:#f5f5f5"></i>agree (miss)</p>
<h2>Summary</h2>
<div class="tblwrap"><table class="sum"><tr><th>case</th><th>mode</th>${tagList.map((t) => `<th>${t}: hover diff px</th><th>${t}: hit diff px</th>`).join('')}</tr>
${rows.map((r) => `<tr><td><a href="#${r.key}">${esc(r.title)}</a></td><td>${r.mode}</td>${tagList.map((t) => `<td>${r.stats[t]?.hoverDiffPx ?? '-'}</td><td class="${(r.stats[t]?.hitDiffPx ?? 1) ? 'bad' : 'ok'}">${r.stats[t]?.hitDiffPx ?? '-'}</td>`).join('')}</tr>`).join('\n')}
</table></div>
<p class="lead">${tagList.map((t) => { const x = totals(t); return x ? `${t}: <b class="${x.bad ? 'bad' : 'ok'}">${x.bad} of ${x.n}</b> cases differ from OSS in hit area (${x.px} px in total).` : ''; }).join(' ')} Hover-diff counts include ordinary anti-aliasing noise along every edge (Qt vs Canvas); the hit maps are exact.</p>
${groups.map((g) => `<h2>${esc(g)}</h2>` + rows.filter((r) => r.group === g).map(rowHtml).join('\n')).join('\n')}
`;
const reportPath = path.join(outRoot, 'report.html');
writeFileSync(reportPath, html);
console.log('REPORT: ' + reportPath);

let fails = 0;
if (pageErrors.length) { console.log('FAIL  page errors: ' + pageErrors.join(' | ')); fails++; }
for (const r of rows) {
  const s = r.stats[tag];
  if (!s) continue;
  const okCase = s.hitDiffPx <= HIT_TOLERANCE_PX;
  console.log(`${okCase ? 'PASS ' : 'FAIL '} ${r.key}: hit diff ${s.hitDiffPx} px, hover diff ${s.hoverDiffPx} px`);
  if (!okCase) fails++;
}
process.exit(fails ? 1 : 0);
