#!/usr/bin/env python3
"""Bring src/ui/translations.ts up to date with OpenStrand Studio's translations.py.

    python3 tools/sync_translations.py [--oss ../OpenStrandStudio]

The desktop app's table is the source of truth for every language it ships.
This script edits the TypeScript table IN PLACE, line by line, so the comments
and the hand-tuned wording already in it survive:

  * every existing entry gains the languages it is missing (the five added in
    OSS 1.111: ru, fi, sv, ja, zh) from the desktop table, when the desktop
    table has that key;
  * the keys named in FORCE_FROM_OSS are rewritten from the desktop table in
    every language (wording the desktop app changed on purpose);
  * every key the desktop table has that this table lacks is appended, in all
    twelve languages;
  * the Lang type and the Entry interface list all twelve languages;
  * src/store/historyTranslations.ts is regenerated from the desktop's
    undo_redo_translations.py (the undo / redo tooltip action names).

Entries the desktop app does not know (JS-only keys) are left alone: t() falls
back to English for a language they do not carry.
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LANGS = ['en', 'fr', 'de', 'it', 'es', 'pt', 'he', 'ru', 'fi', 'sv', 'ja', 'zh']

# Keys whose wording OSS changed and that this table must follow verbatim.
FORCE_FROM_OSS = {'refresh_tooltip', 'whats_new_info'}

ENTRY_RE = re.compile(r'^  ([A-Za-z0-9_]+): \{ ')
PRESENT_RE = re.compile(r'(?:^|[ {])(' + '|'.join(LANGS) + r'): ')


def literal(value):
    """A TypeScript string literal for `value`."""
    if '\n' in value and len(value) > 120:
        body = value.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
        return '`' + body + '`'
    return json.dumps(value, ensure_ascii=False)


def entry_line(key, table):
    parts = []
    for lang in LANGS:
        if key in table.get(lang, {}):
            parts.append('%s: %s' % (lang, literal(table[lang][key])))
    return '  %s: { %s },' % (key, ', '.join(parts))


def load_oss(oss_root):
    src = os.path.join(oss_root, 'src')
    sys.path.insert(0, src)
    from translations import translations  # noqa: E402
    return translations


def write_history_translations(oss_root):
    """src/store/historyTranslations.ts from undo_redo_translations.py."""
    from undo_redo_translations import ACTION_TRANSLATIONS  # noqa: E402
    out = [
        '// Generated by tools/sync_translations.py from OpenStrandStudio/src/',
        '// undo_redo_translations.py (OSS 1.111 "Translate undo and redo history',
        '// tooltips"): the display name of each stable undo action id, per language.',
        '// English lives in historyMeta.ts ACTIONS; a language or action missing',
        '// here falls back to it. Never stored in snapshots.',
        '',
        'export const ACTION_TRANSLATIONS: Record<string, Record<string, string>> = {',
    ]
    for lang in ['fr', 'de', 'it', 'es', 'pt', 'he', 'ru', 'fi', 'sv', 'ja', 'zh']:
        table = ACTION_TRANSLATIONS.get(lang, {})
        out.append('  %s: {' % lang)
        for action, label in table.items():
            out.append('    %s: %s,' % (json.dumps(action), json.dumps(label, ensure_ascii=False)))
        out.append('  },')
    out.append('};')
    out.append('')
    path = os.path.join(ROOT, 'src', 'store', 'historyTranslations.ts')
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(out))
    print('historyTranslations.ts synced')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--oss', default=os.path.join(ROOT, '..', 'OpenStrandStudio'))
    args = ap.parse_args()
    table = load_oss(args.oss)
    ts_path = os.path.join(ROOT, 'src', 'ui', 'translations.ts')
    with open(ts_path, encoding='utf-8') as fh:
        lines = fh.read().split('\n')

    out = []
    seen = set()
    i = 0
    n = len(lines)
    in_strings = False
    while i < n:
        line = lines[i]
        if line.startswith('export type Lang ='):
            out.append('export type Lang = ' + ' | '.join("'%s'" % l for l in LANGS) + ';')
            i += 1
            continue
        if line.startswith('export interface Entry {'):
            fields = ['en: string'] + ['%s?: string' % l for l in LANGS[1:]]
            out.append('export interface Entry { ' + '; '.join(fields) + '; }')
            i += 1
            continue
        if line.startswith('export const STRINGS'):
            in_strings = True
            out.append(line)
            i += 1
            continue
        if in_strings and line == '};':
            # Append every desktop key this table lacks.
            for key in table['en']:
                if key not in seen:
                    out.append(entry_line(key, table))
            in_strings = False
            out.append(line)
            i += 1
            continue
        m = ENTRY_RE.match(line) if in_strings else None
        if not m:
            out.append(line)
            i += 1
            continue
        key = m.group(1)
        seen.add(key)
        # Extent of the entry: one line, or up to the line closing the record.
        j = i
        while not lines[j].rstrip().endswith('},'):
            j += 1
        block = lines[i:j + 1]
        if key in FORCE_FROM_OSS and key in table['en']:
            out.append(entry_line(key, table))
        else:
            text = '\n'.join(block)
            present = set(PRESENT_RE.findall(text))
            add = [l for l in LANGS if l not in present and key in table.get(l, {})]
            if add:
                extra = ''.join(', %s: %s' % (l, literal(table[l][key])) for l in add)
                last = block[-1].rstrip()
                assert last.endswith(' },'), (key, last)
                block[-1] = last[:-3] + extra + ' },'
            out.extend(block)
        i = j + 1

    with open(ts_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(out))
    print('translations.ts synced: %d entries, %d languages' % (len(seen), len(LANGS)))
    write_history_translations(args.oss)


if __name__ == '__main__':
    main()
